mounts:
  - source: assets
    target: assets
  - source: assets/img/
    target: static/img/
  - source: node_modules/lucide/dist/esm
    target: assets/js/lucide
  - source: node_modules/minireset.css/minireset.css
    target: assets/css/vendor/minireset.css
