mounts:
  - source: assets
    target: assets
  - source: static
    target: static
  - source: assets/img/
    target: static/img/
  - source: node_modules/minireset.css/minireset.css
    target: assets/css/vendor/minireset.css
