homepage_featured:
  - les_meves_ajudes
  - leximpact_socio_fiscal
  - benefitme
showcase:
  author:
    types:
      icons:
        default: user
        individual: user
        collective: users
        ngo: globe
        research_center: graduation-cap
        business: factory
        local_institution: building
        state_institution: landmark
mastodon: https://mastodon.social/@openfisca
slack: https://openfisca.slack.com
github: https://github.com/openfisca/
